### ISSUE TITLE
Installation does not finish successfully

### ISSUE THREAD

**Issue by churnikov** [stsouko/marvin_dash#1]
Hello!

I'm using macOS 10.15.7
npm: '7.13.0',
node: '16.2.0'
pip: 20.3.1

run of `npm install` gives me the following error:

```

> dash-marvinjs@0.1.1 prepublish
> npm run validate-init


> dash-marvinjs@0.1.1 validate-init /Users/nikita/tmp/marvin_dash
> python _validate_init.py

Traceback (most recent call last):
  File "_validate_init.py", line 14, in <module>
    components_lib = importlib.import_module(components_package)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nikita/tmp/marvin_dash/dash_marvinjs/__init__.py", line 10, in <module>
    from ._imports_ import *
  File "/Users/nikita/tmp/marvin_dash/dash_marvinjs/_imports_.py", line 1, in <module>
    from .DashMarvinJS import DashMarvinJS
ModuleNotFoundError: No module named 'dash_marvinjs.DashMarvinJS'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-marvinjs@0.1.1 validate-init: `python _validate_init.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dash-marvinjs@0.1.1 validate-init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikita/.npm/_logs/2021-06-01T14_56_41_782Z-debug.log
npm ERR! code 1
npm ERR! path /Users/nikita/tmp/marvin_dash
npm ERR! command failed
npm ERR! command sh -c npm run validate-init

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikita/.npm/_logs/2021-06-01T14_56_41_818Z-debug.log
```

**Comment by stsouko** [comment]
fixed 3e0db7c.
